- name: software | install multimedia codecs
  tags: packages,system,system-packages,workstation-packages
  package:
    name:
      - "{{ gstreamer_libav_package }}"
      - "{{ gstreamer_plugins_bad_package }}"
