- name: software | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - at
      - colordiff
      - curl
      # - environment-modules
      - fish
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - "{{ rename_package }}"
      - pass
      - rsync
      - screen
      - sshfs
      - tmux
      - traceroute
      - "{{ vim_package }}"
      - unzip
      - wget
      - whois
      - zip

- name: software | utilities | install man-pages (arch)
  tags: packages,system,environment-modules
  pacman:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
