# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

# Load encrypted variables
- include_vars: "secrets.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/adrian.yml
  - import_tasks: users/root.yml

  # install software
  - import_tasks: software/environment_modules.yml
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_utilities.yml

  # Perform remaining tasks:
  - import_tasks: system_setup/clock.yml
  - import_tasks: system_setup/cron.yml
  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/logging.yml
  - import_tasks: system_setup/memory.yml
  - import_tasks: system_setup/microcode.yml
  - import_tasks: system_setup/nvidia.yml
    tags: nvidia
  - import_tasks: system_setup/openssh.yml
  - import_tasks: system_setup/unattended_upgrades.yml
    when:
      - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
      - unattended_upgrades is defined
      - unattended_upgrades == true

  rescue:
    - set_fact: task_failed=true
